// AUTO-GENERATED from shared/contracts/*.v1.json - do not edit manually
// Generated by scripts/gen_contracts_rs.py

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

// TauriCommand local definitions
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriCommandDefAudioDevice {
    pub channels: i64,
    pub is_default: bool,
    pub name: String,
    pub sample_rate: i64,
    pub uid: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriCommandDefCheckItem {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    pub message: String,
    pub status: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriCommandDefDiagnosticsReport {
    pub capabilities: TauriCommandDefOpenObject,
    pub config: TauriCommandDefOpenObject,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub environment: Option<BTreeMap<String, String>>,
    pub platform: String,
    pub recent_logs: Vec<TauriCommandDefLogEntry>,
    pub self_check: TauriCommandDefOpenObject,
    pub version: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriCommandDefEmptyParams {}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriCommandDefLogEntry {
    pub level: String,
    pub message: String,
    pub target: String,
    pub timestamp: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriCommandDefModelCatalogEntry {
    pub default_language: String,
    pub description: String,
    pub display_name: String,
    pub family: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub license_spdx: Option<String>,
    pub manifest_path: String,
    pub model_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub size_bytes: Option<i64>,
    pub supported_languages: Vec<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriCommandDefModelStatus {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    pub model_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub progress: Option<serde_json::Value>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    pub status: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriCommandDefOpenObject {
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriCommandDefPresetInfo {
    pub description: String,
    pub id: String,
    pub name: String,
    pub rule_count: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriCommandDefStateEvent {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    pub enabled: bool,
    pub state: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timestamp: Option<String>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

pub type TauriCommandDefVoidResult = Option<BTreeMap<String, serde_json::Value>>;

// TauriEvent local definitions
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriEventDefAppError {
    pub code: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub details: Option<serde_json::Value>,
    pub message: String,
    pub recoverable: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriEventDefAppErrorPayload {
    pub error: TauriEventDefAppError,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recoverable: Option<bool>,
    pub seq: i64,
}

pub type TauriEventDefAppState = String;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriEventDefAudioLevelPayload {
    pub peak: f64,
    pub rms: f64,
    pub seq: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    pub source: String,
}

pub type TauriEventDefInjectionResult = serde_json::Value;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriEventDefModelProgressPayload {
    pub current: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub current_file: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub files_completed: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub files_total: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_id: Option<String>,
    pub seq: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stage: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriEventDefModelStatusPayload {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    pub model_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub progress: Option<TauriEventDefModelStatusProgress>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    pub seq: i64,
    pub status: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriEventDefModelStatusProgress {
    pub current: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,
    pub unit: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriEventDefRecordingStatusPayload {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub audio_ms: Option<i64>,
    pub phase: String,
    pub seq: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub started_at: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriEventDefSidecarStatusPayload {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    pub restart_count: i64,
    pub seq: i64,
    pub state: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriEventDefStateChangedPayload {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    pub enabled: bool,
    pub seq: i64,
    pub state: TauriEventDefAppState,
    pub timestamp: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriEventDefTranscriptCompletePayload {
    pub entry: TauriEventDefTranscriptEntry,
    pub seq: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriEventDefTranscriptEntry {
    pub audio_duration_ms: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub final_text: Option<String>,
    pub id: String,
    pub injection_result: TauriEventDefInjectionResult,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub raw_text: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    pub text: String,
    pub timestamp: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub timings: Option<TauriEventDefTranscriptTimings>,
    pub transcription_duration_ms: i64,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriEventDefTranscriptErrorPayload {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub app_error: Option<TauriEventDefAppError>,
    pub error: serde_json::Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub recoverable: Option<bool>,
    pub seq: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct TauriEventDefTranscriptTimings {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub inject_ms: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ipc_ms: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub postprocess_ms: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total_ms: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub transcribe_ms: Option<i64>,
}

// SidecarRpc local definitions
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct SidecarRpcDefReplacementRule {
    pub case_sensitive: bool,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub enabled: bool,
    pub id: String,
    pub kind: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub origin: Option<String>,
    pub pattern: String,
    pub replacement: String,
    pub word_boundary: bool,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

// Tauri command constants and payload types
pub const CMD_CAN_START_RECORDING: &str = "can_start_recording";
pub const CMD_CANCEL_RECORDING: &str = "cancel_recording";
pub const CMD_CLEAR_HISTORY: &str = "clear_history";
pub const CMD_COPY_LAST_TRANSCRIPT: &str = "copy_last_transcript";
pub const CMD_COPY_TRANSCRIPT: &str = "copy_transcript";
pub const CMD_DOWNLOAD_MODEL: &str = "download_model";
pub const CMD_EXPORT_HISTORY: &str = "export_history";
pub const CMD_GENERATE_DIAGNOSTICS: &str = "generate_diagnostics";
pub const CMD_GET_APP_STATE: &str = "get_app_state";
pub const CMD_GET_AVAILABLE_PRESETS: &str = "get_available_presets";
pub const CMD_GET_CAPABILITIES: &str = "get_capabilities";
pub const CMD_GET_CAPABILITY_ISSUES: &str = "get_capability_issues";
pub const CMD_GET_CONFIG: &str = "get_config";
pub const CMD_GET_HOTKEY_STATUS: &str = "get_hotkey_status";
pub const CMD_GET_MODEL_CATALOG: &str = "get_model_catalog";
pub const CMD_GET_MODEL_STATUS: &str = "get_model_status";
pub const CMD_GET_RECENT_LOGS: &str = "get_recent_logs";
pub const CMD_GET_REPLACEMENT_RULES: &str = "get_replacement_rules";
pub const CMD_GET_TRANSCRIPT_HISTORY: &str = "get_transcript_history";
pub const CMD_IS_ENABLED: &str = "is_enabled";
pub const CMD_LIST_AUDIO_DEVICES: &str = "list_audio_devices";
pub const CMD_LOAD_PRESET: &str = "load_preset";
pub const CMD_PREVIEW_REPLACEMENT: &str = "preview_replacement";
pub const CMD_PURGE_MODEL_CACHE: &str = "purge_model_cache";
pub const CMD_RESET_CONFIG_TO_DEFAULTS: &str = "reset_config_to_defaults";
pub const CMD_RESTART_SIDECAR: &str = "restart_sidecar";
pub const CMD_RUN_SELF_CHECK: &str = "run_self_check";
pub const CMD_SET_AUDIO_DEVICE: &str = "set_audio_device";
pub const CMD_SET_ENABLED: &str = "set_enabled";
pub const CMD_SET_HOTKEY: &str = "set_hotkey";
pub const CMD_SET_REPLACEMENT_RULES: &str = "set_replacement_rules";
pub const CMD_START_MIC_TEST: &str = "start_mic_test";
pub const CMD_START_RECORDING: &str = "start_recording";
pub const CMD_STOP_MIC_TEST: &str = "stop_mic_test";
pub const CMD_STOP_RECORDING: &str = "stop_recording";
pub const CMD_TOGGLE_ENABLED: &str = "toggle_enabled";
pub const CMD_UPDATE_CONFIG: &str = "update_config";

pub const TAURI_COMMAND_NAMES: &[&str] = &[
    "can_start_recording",
    "cancel_recording",
    "clear_history",
    "copy_last_transcript",
    "copy_transcript",
    "download_model",
    "export_history",
    "generate_diagnostics",
    "get_app_state",
    "get_available_presets",
    "get_capabilities",
    "get_capability_issues",
    "get_config",
    "get_hotkey_status",
    "get_model_catalog",
    "get_model_status",
    "get_recent_logs",
    "get_replacement_rules",
    "get_transcript_history",
    "is_enabled",
    "list_audio_devices",
    "load_preset",
    "preview_replacement",
    "purge_model_cache",
    "reset_config_to_defaults",
    "restart_sidecar",
    "run_self_check",
    "set_audio_device",
    "set_enabled",
    "set_hotkey",
    "set_replacement_rules",
    "start_mic_test",
    "start_recording",
    "stop_mic_test",
    "stop_recording",
    "toggle_enabled",
    "update_config",
];

pub type CommandCanStartRecordingParams = TauriCommandDefEmptyParams;

pub type CommandCanStartRecordingResult = TauriCommandDefVoidResult;

pub type CommandCancelRecordingParams = TauriCommandDefEmptyParams;

pub type CommandCancelRecordingResult = TauriCommandDefOpenObject;

pub type CommandClearHistoryParams = TauriCommandDefEmptyParams;

pub type CommandClearHistoryResult = TauriCommandDefVoidResult;

pub type CommandCopyLastTranscriptParams = TauriCommandDefEmptyParams;

pub type CommandCopyLastTranscriptResult = Option<String>;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct CommandCopyTranscriptParams {
    pub id: String,
}

pub type CommandCopyTranscriptResult = TauriCommandDefVoidResult;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct CommandDownloadModelParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
    #[serde(rename = "modelId", default, skip_serializing_if = "Option::is_none")]
    pub model_id: Option<String>,
    #[serde(rename = "model_id", default, skip_serializing_if = "Option::is_none")]
    pub model_id_2: Option<String>,
}

pub type CommandDownloadModelResult = TauriCommandDefVoidResult;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct CommandExportHistoryParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub path: Option<String>,
}

pub type CommandExportHistoryResult = TauriCommandDefOpenObject;

pub type CommandGenerateDiagnosticsParams = TauriCommandDefEmptyParams;

pub type CommandGenerateDiagnosticsResult = TauriCommandDefDiagnosticsReport;

pub type CommandGetAppStateParams = TauriCommandDefEmptyParams;

pub type CommandGetAppStateResult = TauriCommandDefStateEvent;

pub type CommandGetAvailablePresetsParams = TauriCommandDefEmptyParams;

pub type CommandGetAvailablePresetsResult = Vec<TauriCommandDefPresetInfo>;

pub type CommandGetCapabilitiesParams = TauriCommandDefEmptyParams;

pub type CommandGetCapabilitiesResult = TauriCommandDefOpenObject;

pub type CommandGetCapabilityIssuesParams = TauriCommandDefEmptyParams;

pub type CommandGetCapabilityIssuesResult = Vec<TauriCommandDefOpenObject>;

pub type CommandGetConfigParams = TauriCommandDefEmptyParams;

pub type CommandGetConfigResult = TauriCommandDefOpenObject;

pub type CommandGetHotkeyStatusParams = TauriCommandDefEmptyParams;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct CommandGetHotkeyStatusResult {
    pub copy_last: String,
    pub mode: String,
    pub primary: String,
    pub registered: bool,
}

pub type CommandGetModelCatalogParams = TauriCommandDefEmptyParams;

pub type CommandGetModelCatalogResult = Vec<TauriCommandDefModelCatalogEntry>;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct CommandGetModelStatusParams {
    #[serde(rename = "modelId", default, skip_serializing_if = "Option::is_none")]
    pub model_id: Option<String>,
    #[serde(rename = "model_id", default, skip_serializing_if = "Option::is_none")]
    pub model_id_2: Option<String>,
}

pub type CommandGetModelStatusResult = TauriCommandDefModelStatus;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct CommandGetRecentLogsParams {
    pub count: i64,
}

pub type CommandGetRecentLogsResult = Vec<TauriCommandDefLogEntry>;

pub type CommandGetReplacementRulesParams = TauriCommandDefEmptyParams;

pub type CommandGetReplacementRulesResult = Vec<TauriCommandDefOpenObject>;

pub type CommandGetTranscriptHistoryParams = TauriCommandDefEmptyParams;

pub type CommandGetTranscriptHistoryResult = Vec<TauriCommandDefOpenObject>;

pub type CommandIsEnabledParams = TauriCommandDefEmptyParams;

pub type CommandIsEnabledResult = bool;

pub type CommandListAudioDevicesParams = TauriCommandDefEmptyParams;

pub type CommandListAudioDevicesResult = Vec<TauriCommandDefAudioDevice>;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct CommandLoadPresetParams {
    #[serde(rename = "presetId")]
    pub preset_id: String,
    #[serde(rename = "preset_id", default, skip_serializing_if = "Option::is_none")]
    pub preset_id_2: Option<String>,
}

pub type CommandLoadPresetResult = Vec<TauriCommandDefOpenObject>;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct CommandPreviewReplacementParams {
    pub input: String,
    pub rules: Vec<TauriCommandDefOpenObject>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct CommandPreviewReplacementResult {
    pub applied_rules_count: i64,
    pub result: String,
    pub truncated: bool,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct CommandPurgeModelCacheParams {
    #[serde(rename = "modelId", default, skip_serializing_if = "Option::is_none")]
    pub model_id: Option<String>,
    #[serde(rename = "model_id", default, skip_serializing_if = "Option::is_none")]
    pub model_id_2: Option<String>,
}

pub type CommandPurgeModelCacheResult = TauriCommandDefVoidResult;

pub type CommandResetConfigToDefaultsParams = TauriCommandDefEmptyParams;

pub type CommandResetConfigToDefaultsResult = TauriCommandDefOpenObject;

pub type CommandRestartSidecarParams = TauriCommandDefEmptyParams;

pub type CommandRestartSidecarResult = TauriCommandDefOpenObject;

pub type CommandRunSelfCheckParams = TauriCommandDefEmptyParams;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct CommandRunSelfCheckResult {
    pub hotkey: TauriCommandDefCheckItem,
    pub injection: TauriCommandDefCheckItem,
    pub microphone: TauriCommandDefCheckItem,
    pub model: TauriCommandDefCheckItem,
    pub sidecar: TauriCommandDefCheckItem,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct CommandSetAudioDeviceParams {
    #[serde(rename = "deviceUid", default, skip_serializing_if = "Option::is_none")]
    pub device_uid: Option<String>,
    #[serde(
        rename = "device_uid",
        default,
        skip_serializing_if = "Option::is_none"
    )]
    pub device_uid_2: Option<String>,
}

pub type CommandSetAudioDeviceResult = String;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct CommandSetEnabledParams {
    pub enabled: bool,
}

pub type CommandSetEnabledResult = TauriCommandDefVoidResult;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct CommandSetHotkeyParams {
    #[serde(rename = "copyLast")]
    pub copy_last: String,
    #[serde(rename = "copy_last", default, skip_serializing_if = "Option::is_none")]
    pub copy_last_2: Option<String>,
    pub primary: String,
}

pub type CommandSetHotkeyResult = TauriCommandDefVoidResult;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct CommandSetReplacementRulesParams {
    pub rules: Vec<TauriCommandDefOpenObject>,
}

pub type CommandSetReplacementRulesResult = TauriCommandDefVoidResult;

pub type CommandStartMicTestParams = TauriCommandDefEmptyParams;

pub type CommandStartMicTestResult = TauriCommandDefVoidResult;

pub type CommandStartRecordingParams = TauriCommandDefEmptyParams;

pub type CommandStartRecordingResult = TauriCommandDefOpenObject;

pub type CommandStopMicTestParams = TauriCommandDefEmptyParams;

pub type CommandStopMicTestResult = TauriCommandDefVoidResult;

pub type CommandStopRecordingParams = TauriCommandDefEmptyParams;

pub type CommandStopRecordingResult = TauriCommandDefOpenObject;

pub type CommandToggleEnabledParams = TauriCommandDefEmptyParams;

pub type CommandToggleEnabledResult = bool;

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct CommandUpdateConfigParams {
    pub config: TauriCommandDefOpenObject,
}

pub type CommandUpdateConfigResult = TauriCommandDefVoidResult;

// Tauri event constants and payload types
pub const EVENT_APP_ERROR: &str = "app:error";
pub const EVENT_AUDIO_LEVEL: &str = "audio:level";
pub const EVENT_MODEL_PROGRESS: &str = "model:progress";
pub const EVENT_MODEL_STATUS: &str = "model:status";
pub const EVENT_RECORDING_STATUS: &str = "recording:status";
pub const EVENT_SIDECAR_STATUS: &str = "sidecar:status";
pub const EVENT_SIDECAR_STATUS_LEGACY: &str = "status:changed";
pub const EVENT_STATE_CHANGED: &str = "state:changed";
pub const EVENT_STATE_CHANGED_LEGACY: &str = "state_changed";
pub const EVENT_TRANSCRIPT_COMPLETE: &str = "transcript:complete";
pub const EVENT_TRANSCRIPT_COMPLETE_LEGACY: &str = "transcription:complete";
pub const EVENT_TRANSCRIPT_ERROR: &str = "transcript:error";
pub const EVENT_TRANSCRIPT_ERROR_LEGACY: &str = "transcription:error";

pub const TAURI_EVENT_NAMES: &[&str] = &[
    "app:error",
    "audio:level",
    "model:progress",
    "model:status",
    "recording:status",
    "sidecar:status",
    "state:changed",
    "transcript:complete",
    "transcript:error",
];

pub type EventAppErrorPayload = TauriEventDefAppErrorPayload;

pub type EventAudioLevelPayload = TauriEventDefAudioLevelPayload;

pub type EventModelProgressPayload = TauriEventDefModelProgressPayload;

pub type EventModelStatusPayload = TauriEventDefModelStatusPayload;

pub type EventRecordingStatusPayload = TauriEventDefRecordingStatusPayload;

pub type EventSidecarStatusPayload = TauriEventDefSidecarStatusPayload;

pub type EventStateChangedPayload = TauriEventDefStateChangedPayload;

pub type EventTranscriptCompletePayload = TauriEventDefTranscriptCompletePayload;

pub type EventTranscriptErrorPayload = TauriEventDefTranscriptErrorPayload;

// Sidecar RPC method constants and payload types
pub const RPC_ASR_INITIALIZE: &str = "asr.initialize";
pub const RPC_ASR_STATUS: &str = "asr.status";
pub const RPC_ASR_TRANSCRIBE: &str = "asr.transcribe";
pub const RPC_AUDIO_LIST_DEVICES: &str = "audio.list_devices";
pub const RPC_AUDIO_METER_START: &str = "audio.meter_start";
pub const RPC_AUDIO_METER_STATUS: &str = "audio.meter_status";
pub const RPC_AUDIO_METER_STOP: &str = "audio.meter_stop";
pub const RPC_AUDIO_SET_DEVICE: &str = "audio.set_device";
pub const RPC_MODEL_DOWNLOAD: &str = "model.download";
pub const RPC_MODEL_GET_STATUS: &str = "model.get_status";
pub const RPC_MODEL_INSTALL: &str = "model.install";
pub const RPC_MODEL_PURGE_CACHE: &str = "model.purge_cache";
pub const RPC_RECORDING_CANCEL: &str = "recording.cancel";
pub const RPC_RECORDING_START: &str = "recording.start";
pub const RPC_RECORDING_STATUS: &str = "recording.status";
pub const RPC_RECORDING_STOP: &str = "recording.stop";
pub const RPC_REPLACEMENTS_GET_PRESET_RULES: &str = "replacements.get_preset_rules";
pub const RPC_REPLACEMENTS_GET_PRESETS: &str = "replacements.get_presets";
pub const RPC_REPLACEMENTS_GET_RULES: &str = "replacements.get_rules";
pub const RPC_REPLACEMENTS_PREVIEW: &str = "replacements.preview";
pub const RPC_REPLACEMENTS_SET_RULES: &str = "replacements.set_rules";
pub const RPC_STATUS_GET: &str = "status.get";
pub const RPC_SYSTEM_INFO: &str = "system.info";
pub const RPC_SYSTEM_PING: &str = "system.ping";
pub const RPC_SYSTEM_SHUTDOWN: &str = "system.shutdown";

pub const SIDECAR_RPC_METHOD_NAMES: &[&str] = &[
    "asr.initialize",
    "asr.status",
    "asr.transcribe",
    "audio.list_devices",
    "audio.meter_start",
    "audio.meter_status",
    "audio.meter_stop",
    "audio.set_device",
    "model.download",
    "model.get_status",
    "model.install",
    "model.purge_cache",
    "recording.cancel",
    "recording.start",
    "recording.status",
    "recording.stop",
    "replacements.get_preset_rules",
    "replacements.get_presets",
    "replacements.get_rules",
    "replacements.preview",
    "replacements.set_rules",
    "status.get",
    "system.info",
    "system.ping",
    "system.shutdown",
];

pub const SIDECAR_RPC_REQUIRED_METHOD_NAMES: &[&str] = &[
    "asr.initialize",
    "audio.list_devices",
    "audio.meter_start",
    "audio.meter_stop",
    "audio.set_device",
    "model.get_status",
    "model.purge_cache",
    "recording.cancel",
    "recording.start",
    "recording.stop",
    "replacements.set_rules",
    "status.get",
    "system.info",
    "system.ping",
    "system.shutdown",
];

pub const SIDECAR_RPC_OPTIONAL_METHOD_NAMES: &[&str] = &[
    "asr.status",
    "asr.transcribe",
    "audio.meter_status",
    "model.download",
    "model.install",
    "recording.status",
    "replacements.get_preset_rules",
    "replacements.get_presets",
    "replacements.get_rules",
    "replacements.preview",
];

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcAsrInitializeParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_pref: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcAsrInitializeResult {
    pub device: String,
    pub model_id: String,
    pub status: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcAsrStatusParams {}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcAsrStatusResult {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_id: Option<String>,
    pub ready: bool,
    pub state: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcAsrTranscribeParams {
    pub audio_path: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcAsrTranscribeResult {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub language: Option<String>,
    pub text: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcAudioListDevicesParams {}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcAudioListDevicesResult {
    pub devices: Vec<BTreeMap<String, serde_json::Value>>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcAudioMeterStartParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_uid: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interval_ms: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcAudioMeterStartResult {
    pub interval_ms: i64,
    pub running: bool,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcAudioMeterStatusParams {}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcAudioMeterStatusResult {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub interval_ms: Option<i64>,
    pub running: bool,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcAudioMeterStopParams {}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcAudioMeterStopResult {
    pub stopped: bool,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcAudioSetDeviceParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_uid: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcAudioSetDeviceResult {
    pub active_device_uid: Option<String>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcModelDownloadParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_id: Option<String>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcModelDownloadResult {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub progress: Option<BTreeMap<String, serde_json::Value>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    pub status: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcModelGetStatusParams {}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcModelGetStatusResult {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub progress: Option<BTreeMap<String, serde_json::Value>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    pub status: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcModelInstallParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_id: Option<String>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcModelInstallResult {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub cache_path: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_id: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub progress: Option<BTreeMap<String, serde_json::Value>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub revision: Option<String>,
    pub status: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcModelPurgeCacheParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model_id: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcModelPurgeCacheResult {
    pub purged: bool,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcRecordingCancelParams {
    pub session_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcRecordingCancelResult {
    pub cancelled: bool,
    pub session_id: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcRecordingStartParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub device_uid: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcRecordingStartResult {
    pub session_id: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcRecordingStatusParams {}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcRecordingStatusResult {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_ms: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub elapsed_sec: Option<f64>,
    pub session_id: Option<String>,
    pub state: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcRecordingStopParams {
    pub session_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcRecordingStopResult {
    pub audio_duration_ms: i64,
    pub channels: i64,
    pub sample_rate: i64,
    pub session_id: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcReplacementsGetPresetRulesParams {
    pub preset_id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcReplacementsGetPresetRulesResult {
    pub preset: serde_json::Value,
    pub rules: Vec<SidecarRpcDefReplacementRule>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcReplacementsGetPresetsParams {}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcReplacementsGetPresetsResult {
    pub presets: Vec<serde_json::Value>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcReplacementsGetRulesParams {}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcReplacementsGetRulesResult {
    pub rules: Vec<SidecarRpcDefReplacementRule>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcReplacementsPreviewParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rules: Option<Vec<SidecarRpcDefReplacementRule>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub skip_macros: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub skip_normalize: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub text: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcReplacementsPreviewResult {
    pub result: String,
    pub truncated: bool,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcReplacementsSetRulesParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub rules: Option<Vec<SidecarRpcDefReplacementRule>>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcReplacementsSetRulesResult {
    pub count: i64,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcStatusGetParams {}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcStatusGetResult {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<serde_json::Value>,
    pub state: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcSystemInfoParams {}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcSystemInfoResult {
    pub capabilities: Vec<String>,
    pub protocol: String,
    pub runtime: serde_json::Value,
    pub version: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcSystemPingParams {}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcSystemPingResult {
    pub protocol: String,
    pub version: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcSystemShutdownParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub reason: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcSystemShutdownResult {
    pub status: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

// Sidecar RPC notification constants and payload types
pub const RPC_NOTIFY_EVENT_AUDIO_LEVEL: &str = "event.audio_level";
pub const RPC_NOTIFY_EVENT_MODEL_PROGRESS: &str = "event.model_progress";
pub const RPC_NOTIFY_EVENT_STATUS_CHANGED: &str = "event.status_changed";
pub const RPC_NOTIFY_EVENT_TRANSCRIPTION_COMPLETE: &str = "event.transcription_complete";
pub const RPC_NOTIFY_EVENT_TRANSCRIPTION_ERROR: &str = "event.transcription_error";

pub const SIDECAR_RPC_NOTIFICATION_NAMES: &[&str] = &[
    "event.audio_level",
    "event.model_progress",
    "event.status_changed",
    "event.transcription_complete",
    "event.transcription_error",
];

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcNotificationEventAudioLevelParams {
    pub peak: f64,
    pub rms: f64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub session_id: Option<String>,
    pub source: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcNotificationEventModelProgressParams {
    pub current: i64,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub current_file: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub files_completed: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub files_total: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub stage: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub total: Option<i64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub unit: Option<String>,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcNotificationEventStatusChangedParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub detail: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub model: Option<BTreeMap<String, serde_json::Value>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub progress: Option<BTreeMap<String, serde_json::Value>>,
    pub state: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcNotificationEventTranscriptionCompleteParams {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confidence: Option<f64>,
    pub duration_ms: i64,
    pub session_id: String,
    pub text: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Default)]
pub struct RpcNotificationEventTranscriptionErrorParams {
    pub kind: String,
    pub message: String,
    pub session_id: String,
    #[serde(flatten)]
    pub extra: BTreeMap<String, serde_json::Value>,
}
