/*
 * AUTO-GENERATED FILE. DO NOT EDIT.
 *
 * Generated by: scripts/gen_contracts_ts.py
 * Sources:
 * - shared/contracts/tauri.commands.v1.json
 * - shared/contracts/tauri.events.v1.json
 * - shared/contracts/sidecar.rpc.v1.json
 *
 * Regenerate with: python scripts/gen_contracts_ts.py
 */

// TauriCommand local definitions
export type TauriCommandDefAudioDevice = {
  channels: number;
  is_default: boolean;
  name: string;
  sample_rate: number;
  uid: string;
};

export type TauriCommandDefCheckItem = {
  detail?: string | null;
  message: string;
  status: "ok" | "warning" | "error";
};

export type TauriCommandDefDiagnosticsReport = {
  capabilities: TauriCommandDefOpenObject;
  config: TauriCommandDefOpenObject;
  environment?: Record<string, string>;
  platform: string;
  recent_logs: Array<TauriCommandDefLogEntry>;
  self_check: TauriCommandDefOpenObject;
  version: string;
};

export type TauriCommandDefEmptyParams = {
};

export type TauriCommandDefLogEntry = {
  level: string;
  message: string;
  target: string;
  timestamp: string;
};

export type TauriCommandDefModelCatalogEntry = {
  default_language: string;
  description: string;
  display_name: string;
  family: string;
  license_spdx?: string | null;
  manifest_path: string;
  model_id: string;
  size_bytes?: number | null;
  supported_languages: Array<string>;
};

export type TauriCommandDefModelStatus = {
  cache_path?: string | null;
  error?: string | null;
  model_id: string;
  progress?: {
  current: number;
  total?: number | null;
  unit: string;
} | null;
  revision?: string | null;
  status: "missing" | "downloading" | "loading" | "verifying" | "ready" | "error" | "unknown";
};

export type TauriCommandDefOpenObject = Record<string, unknown>;

export type TauriCommandDefPresetInfo = {
  description: string;
  id: string;
  name: string;
  rule_count: number;
};

export type TauriCommandDefStateEvent = {
  detail?: string | null;
  enabled: boolean;
  state: "idle" | "loading_model" | "recording" | "transcribing" | "error";
  timestamp?: string;
  [key: string]: unknown;
};

export type TauriCommandDefVoidResult = null | Record<string, unknown>;

// TauriEvent local definitions
export type TauriEventDefAppError = {
  code: string;
  details?: unknown;
  message: string;
  recoverable: boolean;
};

export type TauriEventDefAppErrorPayload = {
  error: TauriEventDefAppError;
  message?: string;
  recoverable?: boolean;
  seq: number;
};

export type TauriEventDefAppState = "idle" | "loading_model" | "recording" | "transcribing" | "error";

export type TauriEventDefAudioLevelPayload = {
  peak: number;
  rms: number;
  seq: number;
  session_id?: string;
  source: string;
};

export type TauriEventDefInjectionResult = {
  status: "injected";
  [key: string]: unknown;
} | {
  reason: string;
  status: "clipboard_only";
  [key: string]: unknown;
} | {
  error?: string;
  message?: string;
  status: "error" | "failed";
  [key: string]: unknown;
};

export type TauriEventDefModelProgressPayload = {
  current: number;
  current_file?: string;
  files_completed?: number;
  files_total?: number;
  model_id?: string;
  seq: number;
  stage?: string;
  total?: number | null;
  unit: string;
};

export type TauriEventDefModelStatusPayload = {
  cache_path?: string | null;
  error?: string | null;
  model_id: string;
  progress?: TauriEventDefModelStatusProgress | null;
  revision?: string | null;
  seq: number;
  status: "missing" | "downloading" | "loading" | "verifying" | "ready" | "error" | "unknown";
};

export type TauriEventDefModelStatusProgress = {
  current: number;
  total?: number | null;
  unit: string;
};

export type TauriEventDefRecordingStatusPayload = {
  audio_ms?: number;
  phase: "idle" | "recording" | "transcribing";
  seq: number;
  session_id?: string;
  started_at?: string;
};

export type TauriEventDefSidecarStatusPayload = {
  message?: string;
  restart_count: number;
  seq: number;
  state: "starting" | "ready" | "failed" | "restarting" | "stopped";
};

export type TauriEventDefStateChangedPayload = {
  detail?: string | null;
  enabled: boolean;
  seq: number;
  state: TauriEventDefAppState;
  timestamp: string;
};

export type TauriEventDefTranscriptCompletePayload = {
  entry: TauriEventDefTranscriptEntry;
  seq: number;
};

export type TauriEventDefTranscriptEntry = {
  audio_duration_ms: number;
  confidence?: number;
  final_text?: string;
  id: string;
  injection_result: TauriEventDefInjectionResult;
  language?: string;
  raw_text?: string;
  session_id?: string;
  text: string;
  timestamp: string;
  timings?: TauriEventDefTranscriptTimings;
  transcription_duration_ms: number;
  [key: string]: unknown;
};

export type TauriEventDefTranscriptErrorPayload = {
  app_error?: TauriEventDefAppError;
  error: TauriEventDefAppError | string;
  message?: string;
  recoverable?: boolean;
  seq: number;
  session_id?: string;
};

export type TauriEventDefTranscriptTimings = {
  inject_ms?: number;
  ipc_ms?: number;
  postprocess_ms?: number;
  total_ms?: number;
  transcribe_ms?: number;
};

// SidecarRpc local definitions
export type SidecarRpcDefReplacementRule = {
  case_sensitive: boolean;
  description?: string;
  enabled: boolean;
  id: string;
  kind: "literal" | "regex";
  origin?: "user" | "preset";
  pattern: string;
  replacement: string;
  word_boundary: boolean;
  [key: string]: unknown;
};

// Tauri command params/results
export type TauriCommandCanStartRecordingParams = TauriCommandDefEmptyParams;
export type TauriCommandCanStartRecordingResult = TauriCommandDefVoidResult;

export type TauriCommandCancelRecordingParams = TauriCommandDefEmptyParams;
export type TauriCommandCancelRecordingResult = TauriCommandDefOpenObject;

export type TauriCommandClearHistoryParams = TauriCommandDefEmptyParams;
export type TauriCommandClearHistoryResult = TauriCommandDefVoidResult;

export type TauriCommandCopyLastTranscriptParams = TauriCommandDefEmptyParams;
export type TauriCommandCopyLastTranscriptResult = string | null;

export type TauriCommandCopyTranscriptParams = {
  id: string;
};
export type TauriCommandCopyTranscriptResult = TauriCommandDefVoidResult;

export type TauriCommandDownloadModelParams = {
  force?: boolean | null;
  modelId?: string | null;
  model_id?: string | null;
};
export type TauriCommandDownloadModelResult = TauriCommandDefVoidResult;

export type TauriCommandExportHistoryParams = {
  format?: "json" | "csv";
  path?: string;
};
export type TauriCommandExportHistoryResult = TauriCommandDefOpenObject;

export type TauriCommandGenerateDiagnosticsParams = TauriCommandDefEmptyParams;
export type TauriCommandGenerateDiagnosticsResult = TauriCommandDefDiagnosticsReport;

export type TauriCommandGetAppStateParams = TauriCommandDefEmptyParams;
export type TauriCommandGetAppStateResult = TauriCommandDefStateEvent;

export type TauriCommandGetAvailablePresetsParams = TauriCommandDefEmptyParams;
export type TauriCommandGetAvailablePresetsResult = Array<TauriCommandDefPresetInfo>;

export type TauriCommandGetCapabilitiesParams = TauriCommandDefEmptyParams;
export type TauriCommandGetCapabilitiesResult = TauriCommandDefOpenObject;

export type TauriCommandGetCapabilityIssuesParams = TauriCommandDefEmptyParams;
export type TauriCommandGetCapabilityIssuesResult = Array<TauriCommandDefOpenObject>;

export type TauriCommandGetConfigParams = TauriCommandDefEmptyParams;
export type TauriCommandGetConfigResult = TauriCommandDefOpenObject;

export type TauriCommandGetHotkeyStatusParams = TauriCommandDefEmptyParams;
export type TauriCommandGetHotkeyStatusResult = {
  copy_last: string;
  mode: string;
  primary: string;
  registered: boolean;
};

export type TauriCommandGetModelCatalogParams = TauriCommandDefEmptyParams;
export type TauriCommandGetModelCatalogResult = Array<TauriCommandDefModelCatalogEntry>;

export type TauriCommandGetModelStatusParams = {
  modelId?: string | null;
  model_id?: string | null;
};
export type TauriCommandGetModelStatusResult = TauriCommandDefModelStatus;

export type TauriCommandGetRecentLogsParams = {
  count: number;
};
export type TauriCommandGetRecentLogsResult = Array<TauriCommandDefLogEntry>;

export type TauriCommandGetReplacementRulesParams = TauriCommandDefEmptyParams;
export type TauriCommandGetReplacementRulesResult = Array<TauriCommandDefOpenObject>;

export type TauriCommandGetTranscriptHistoryParams = TauriCommandDefEmptyParams;
export type TauriCommandGetTranscriptHistoryResult = Array<TauriCommandDefOpenObject>;

export type TauriCommandIsEnabledParams = TauriCommandDefEmptyParams;
export type TauriCommandIsEnabledResult = boolean;

export type TauriCommandListAudioDevicesParams = TauriCommandDefEmptyParams;
export type TauriCommandListAudioDevicesResult = Array<TauriCommandDefAudioDevice>;

export type TauriCommandLoadPresetParams = {
  presetId: string;
  preset_id?: string;
};
export type TauriCommandLoadPresetResult = Array<TauriCommandDefOpenObject>;

export type TauriCommandPreviewReplacementParams = {
  input: string;
  rules: Array<TauriCommandDefOpenObject>;
};
export type TauriCommandPreviewReplacementResult = {
  applied_rules_count: number;
  result: string;
  truncated: boolean;
};

export type TauriCommandPurgeModelCacheParams = {
  modelId?: string | null;
  model_id?: string | null;
};
export type TauriCommandPurgeModelCacheResult = TauriCommandDefVoidResult;

export type TauriCommandResetConfigToDefaultsParams = TauriCommandDefEmptyParams;
export type TauriCommandResetConfigToDefaultsResult = TauriCommandDefOpenObject;

export type TauriCommandRestartSidecarParams = TauriCommandDefEmptyParams;
export type TauriCommandRestartSidecarResult = TauriCommandDefOpenObject;

export type TauriCommandRunSelfCheckParams = TauriCommandDefEmptyParams;
export type TauriCommandRunSelfCheckResult = {
  hotkey: TauriCommandDefCheckItem;
  injection: TauriCommandDefCheckItem;
  microphone: TauriCommandDefCheckItem;
  model: TauriCommandDefCheckItem;
  sidecar: TauriCommandDefCheckItem;
};

export type TauriCommandSetAudioDeviceParams = {
  deviceUid?: string | null;
  device_uid?: string | null;
};
export type TauriCommandSetAudioDeviceResult = string;

export type TauriCommandSetEnabledParams = {
  enabled: boolean;
};
export type TauriCommandSetEnabledResult = TauriCommandDefVoidResult;

export type TauriCommandSetHotkeyParams = {
  copyLast: string;
  copy_last?: string;
  primary: string;
};
export type TauriCommandSetHotkeyResult = TauriCommandDefVoidResult;

export type TauriCommandSetReplacementRulesParams = {
  rules: Array<TauriCommandDefOpenObject>;
};
export type TauriCommandSetReplacementRulesResult = TauriCommandDefVoidResult;

export type TauriCommandStartMicTestParams = TauriCommandDefEmptyParams;
export type TauriCommandStartMicTestResult = TauriCommandDefVoidResult;

export type TauriCommandStartRecordingParams = TauriCommandDefEmptyParams;
export type TauriCommandStartRecordingResult = TauriCommandDefOpenObject;

export type TauriCommandStopMicTestParams = TauriCommandDefEmptyParams;
export type TauriCommandStopMicTestResult = TauriCommandDefVoidResult;

export type TauriCommandStopRecordingParams = TauriCommandDefEmptyParams;
export type TauriCommandStopRecordingResult = TauriCommandDefOpenObject;

export type TauriCommandToggleEnabledParams = TauriCommandDefEmptyParams;
export type TauriCommandToggleEnabledResult = boolean;

export type TauriCommandUpdateConfigParams = {
  config: TauriCommandDefOpenObject;
};
export type TauriCommandUpdateConfigResult = TauriCommandDefVoidResult;

export type TauriCommandName = "can_start_recording" | "cancel_recording" | "clear_history" | "copy_last_transcript" | "copy_transcript" | "download_model" | "export_history" | "generate_diagnostics" | "get_app_state" | "get_available_presets" | "get_capabilities" | "get_capability_issues" | "get_config" | "get_hotkey_status" | "get_model_catalog" | "get_model_status" | "get_recent_logs" | "get_replacement_rules" | "get_transcript_history" | "is_enabled" | "list_audio_devices" | "load_preset" | "preview_replacement" | "purge_model_cache" | "reset_config_to_defaults" | "restart_sidecar" | "run_self_check" | "set_audio_device" | "set_enabled" | "set_hotkey" | "set_replacement_rules" | "start_mic_test" | "start_recording" | "stop_mic_test" | "stop_recording" | "toggle_enabled" | "update_config";
export interface TauriCommandParamsMap {
  "can_start_recording": TauriCommandCanStartRecordingParams;
  "cancel_recording": TauriCommandCancelRecordingParams;
  "clear_history": TauriCommandClearHistoryParams;
  "copy_last_transcript": TauriCommandCopyLastTranscriptParams;
  "copy_transcript": TauriCommandCopyTranscriptParams;
  "download_model": TauriCommandDownloadModelParams;
  "export_history": TauriCommandExportHistoryParams;
  "generate_diagnostics": TauriCommandGenerateDiagnosticsParams;
  "get_app_state": TauriCommandGetAppStateParams;
  "get_available_presets": TauriCommandGetAvailablePresetsParams;
  "get_capabilities": TauriCommandGetCapabilitiesParams;
  "get_capability_issues": TauriCommandGetCapabilityIssuesParams;
  "get_config": TauriCommandGetConfigParams;
  "get_hotkey_status": TauriCommandGetHotkeyStatusParams;
  "get_model_catalog": TauriCommandGetModelCatalogParams;
  "get_model_status": TauriCommandGetModelStatusParams;
  "get_recent_logs": TauriCommandGetRecentLogsParams;
  "get_replacement_rules": TauriCommandGetReplacementRulesParams;
  "get_transcript_history": TauriCommandGetTranscriptHistoryParams;
  "is_enabled": TauriCommandIsEnabledParams;
  "list_audio_devices": TauriCommandListAudioDevicesParams;
  "load_preset": TauriCommandLoadPresetParams;
  "preview_replacement": TauriCommandPreviewReplacementParams;
  "purge_model_cache": TauriCommandPurgeModelCacheParams;
  "reset_config_to_defaults": TauriCommandResetConfigToDefaultsParams;
  "restart_sidecar": TauriCommandRestartSidecarParams;
  "run_self_check": TauriCommandRunSelfCheckParams;
  "set_audio_device": TauriCommandSetAudioDeviceParams;
  "set_enabled": TauriCommandSetEnabledParams;
  "set_hotkey": TauriCommandSetHotkeyParams;
  "set_replacement_rules": TauriCommandSetReplacementRulesParams;
  "start_mic_test": TauriCommandStartMicTestParams;
  "start_recording": TauriCommandStartRecordingParams;
  "stop_mic_test": TauriCommandStopMicTestParams;
  "stop_recording": TauriCommandStopRecordingParams;
  "toggle_enabled": TauriCommandToggleEnabledParams;
  "update_config": TauriCommandUpdateConfigParams;
}
export interface TauriCommandResultMap {
  "can_start_recording": TauriCommandCanStartRecordingResult;
  "cancel_recording": TauriCommandCancelRecordingResult;
  "clear_history": TauriCommandClearHistoryResult;
  "copy_last_transcript": TauriCommandCopyLastTranscriptResult;
  "copy_transcript": TauriCommandCopyTranscriptResult;
  "download_model": TauriCommandDownloadModelResult;
  "export_history": TauriCommandExportHistoryResult;
  "generate_diagnostics": TauriCommandGenerateDiagnosticsResult;
  "get_app_state": TauriCommandGetAppStateResult;
  "get_available_presets": TauriCommandGetAvailablePresetsResult;
  "get_capabilities": TauriCommandGetCapabilitiesResult;
  "get_capability_issues": TauriCommandGetCapabilityIssuesResult;
  "get_config": TauriCommandGetConfigResult;
  "get_hotkey_status": TauriCommandGetHotkeyStatusResult;
  "get_model_catalog": TauriCommandGetModelCatalogResult;
  "get_model_status": TauriCommandGetModelStatusResult;
  "get_recent_logs": TauriCommandGetRecentLogsResult;
  "get_replacement_rules": TauriCommandGetReplacementRulesResult;
  "get_transcript_history": TauriCommandGetTranscriptHistoryResult;
  "is_enabled": TauriCommandIsEnabledResult;
  "list_audio_devices": TauriCommandListAudioDevicesResult;
  "load_preset": TauriCommandLoadPresetResult;
  "preview_replacement": TauriCommandPreviewReplacementResult;
  "purge_model_cache": TauriCommandPurgeModelCacheResult;
  "reset_config_to_defaults": TauriCommandResetConfigToDefaultsResult;
  "restart_sidecar": TauriCommandRestartSidecarResult;
  "run_self_check": TauriCommandRunSelfCheckResult;
  "set_audio_device": TauriCommandSetAudioDeviceResult;
  "set_enabled": TauriCommandSetEnabledResult;
  "set_hotkey": TauriCommandSetHotkeyResult;
  "set_replacement_rules": TauriCommandSetReplacementRulesResult;
  "start_mic_test": TauriCommandStartMicTestResult;
  "start_recording": TauriCommandStartRecordingResult;
  "stop_mic_test": TauriCommandStopMicTestResult;
  "stop_recording": TauriCommandStopRecordingResult;
  "toggle_enabled": TauriCommandToggleEnabledResult;
  "update_config": TauriCommandUpdateConfigResult;
}

// Tauri event payloads
export type TauriEventAppErrorPayload = TauriEventDefAppErrorPayload;

export type TauriEventAudioLevelPayload = TauriEventDefAudioLevelPayload;

export type TauriEventModelProgressPayload = TauriEventDefModelProgressPayload;

export type TauriEventModelStatusPayload = TauriEventDefModelStatusPayload;

export type TauriEventRecordingStatusPayload = TauriEventDefRecordingStatusPayload;

export type TauriEventSidecarStatusPayload = TauriEventDefSidecarStatusPayload;

export type TauriEventStateChangedPayload = TauriEventDefStateChangedPayload;

export type TauriEventTranscriptCompletePayload = TauriEventDefTranscriptCompletePayload;

export type TauriEventTranscriptErrorPayload = TauriEventDefTranscriptErrorPayload;

export type TauriEventName = "app:error" | "audio:level" | "model:progress" | "model:status" | "recording:status" | "sidecar:status" | "state:changed" | "transcript:complete" | "transcript:error";
export interface TauriEventPayloadMap {
  "app:error": TauriEventAppErrorPayload;
  "audio:level": TauriEventAudioLevelPayload;
  "model:progress": TauriEventModelProgressPayload;
  "model:status": TauriEventModelStatusPayload;
  "recording:status": TauriEventRecordingStatusPayload;
  "sidecar:status": TauriEventSidecarStatusPayload;
  "state:changed": TauriEventStateChangedPayload;
  "transcript:complete": TauriEventTranscriptCompletePayload;
  "transcript:error": TauriEventTranscriptErrorPayload;
}

// Sidecar RPC method params/results
export type SidecarRpcMethodAsrInitializeParams = {
  device_pref?: "auto" | "cuda" | "cpu";
  language?: string | null;
  model_id?: string;
};
export type SidecarRpcMethodAsrInitializeResult = {
  device: string;
  model_id: string;
  status: string;
  [key: string]: unknown;
};

export type SidecarRpcMethodAsrStatusParams = {
};
export type SidecarRpcMethodAsrStatusResult = {
  device?: string;
  model_id?: string | null;
  ready: boolean;
  state: "uninitialized" | "downloading" | "loading" | "ready" | "error";
  [key: string]: unknown;
};

export type SidecarRpcMethodAsrTranscribeParams = {
  audio_path: string;
  language?: string;
  session_id?: string;
  [key: string]: unknown;
};
export type SidecarRpcMethodAsrTranscribeResult = {
  confidence?: number;
  duration_ms?: number;
  language?: string;
  text: string;
  [key: string]: unknown;
};

export type SidecarRpcMethodAudioListDevicesParams = {
};
export type SidecarRpcMethodAudioListDevicesResult = {
  devices: Array<Record<string, unknown>>;
  [key: string]: unknown;
};

export type SidecarRpcMethodAudioMeterStartParams = {
  device_uid?: string | null;
  interval_ms?: number;
};
export type SidecarRpcMethodAudioMeterStartResult = {
  interval_ms: number;
  running: boolean;
  [key: string]: unknown;
};

export type SidecarRpcMethodAudioMeterStatusParams = {
};
export type SidecarRpcMethodAudioMeterStatusResult = {
  interval_ms?: number;
  running: boolean;
  [key: string]: unknown;
};

export type SidecarRpcMethodAudioMeterStopParams = {
};
export type SidecarRpcMethodAudioMeterStopResult = {
  stopped: boolean;
  [key: string]: unknown;
};

export type SidecarRpcMethodAudioSetDeviceParams = {
  device_uid?: string | null;
};
export type SidecarRpcMethodAudioSetDeviceResult = {
  active_device_uid: string | null;
  [key: string]: unknown;
};

export type SidecarRpcMethodModelDownloadParams = {
  model_id?: string;
  [key: string]: unknown;
};
export type SidecarRpcMethodModelDownloadResult = {
  cache_path?: string;
  error_message?: string;
  model_id?: string;
  progress?: Record<string, unknown>;
  revision?: string;
  status: "missing" | "downloading" | "verifying" | "ready" | "error";
  [key: string]: unknown;
};

export type SidecarRpcMethodModelGetStatusParams = {
};
export type SidecarRpcMethodModelGetStatusResult = {
  cache_path?: string;
  error_message?: string;
  model_id?: string;
  progress?: Record<string, unknown>;
  revision?: string;
  status: "missing" | "downloading" | "verifying" | "ready" | "error";
  [key: string]: unknown;
};

export type SidecarRpcMethodModelInstallParams = {
  model_id?: string;
  [key: string]: unknown;
};
export type SidecarRpcMethodModelInstallResult = {
  cache_path?: string;
  error_message?: string;
  model_id?: string;
  progress?: Record<string, unknown>;
  revision?: string;
  status: "missing" | "downloading" | "verifying" | "ready" | "error";
  [key: string]: unknown;
};

export type SidecarRpcMethodModelPurgeCacheParams = {
  model_id?: string;
};
export type SidecarRpcMethodModelPurgeCacheResult = {
  purged: boolean;
  [key: string]: unknown;
};

export type SidecarRpcMethodRecordingCancelParams = {
  session_id: string;
};
export type SidecarRpcMethodRecordingCancelResult = {
  cancelled: boolean;
  session_id: string;
  [key: string]: unknown;
};

export type SidecarRpcMethodRecordingStartParams = {
  device_uid?: string | null;
  session_id?: string;
  [key: string]: unknown;
};
export type SidecarRpcMethodRecordingStartResult = {
  session_id: string;
  [key: string]: unknown;
};

export type SidecarRpcMethodRecordingStatusParams = {
};
export type SidecarRpcMethodRecordingStatusResult = {
  duration_ms?: number;
  elapsed_sec?: number;
  session_id: string | null;
  state: "idle" | "recording" | "stopping";
  [key: string]: unknown;
};

export type SidecarRpcMethodRecordingStopParams = {
  session_id: string;
};
export type SidecarRpcMethodRecordingStopResult = {
  audio_duration_ms: number;
  channels: number;
  sample_rate: number;
  session_id: string;
  [key: string]: unknown;
};

export type SidecarRpcMethodReplacementsGetPresetRulesParams = {
  preset_id: string;
};
export type SidecarRpcMethodReplacementsGetPresetRulesResult = {
  preset: {
  description: string;
  id: string;
  name: string;
  rule_count: number;
  [key: string]: unknown;
};
  rules: Array<SidecarRpcDefReplacementRule>;
  [key: string]: unknown;
};

export type SidecarRpcMethodReplacementsGetPresetsParams = {
};
export type SidecarRpcMethodReplacementsGetPresetsResult = {
  presets: Array<{
  description: string;
  id: string;
  name: string;
  rule_count: number;
  [key: string]: unknown;
}>;
  [key: string]: unknown;
};

export type SidecarRpcMethodReplacementsGetRulesParams = {
};
export type SidecarRpcMethodReplacementsGetRulesResult = {
  rules: Array<SidecarRpcDefReplacementRule>;
  [key: string]: unknown;
};

export type SidecarRpcMethodReplacementsPreviewParams = {
  rules?: Array<SidecarRpcDefReplacementRule>;
  skip_macros?: boolean;
  skip_normalize?: boolean;
  text?: string;
};
export type SidecarRpcMethodReplacementsPreviewResult = {
  applied_rules_count: number;
  result: string;
  truncated: boolean;
  [key: string]: unknown;
};

export type SidecarRpcMethodReplacementsSetRulesParams = {
  rules?: Array<SidecarRpcDefReplacementRule>;
};
export type SidecarRpcMethodReplacementsSetRulesResult = {
  count: number;
  [key: string]: unknown;
};

export type SidecarRpcMethodStatusGetParams = {
};
export type SidecarRpcMethodStatusGetResult = {
  detail?: string;
  model?: {
  model_id: string;
  status: "missing" | "downloading" | "verifying" | "ready" | "error";
  [key: string]: unknown;
};
  state: "idle" | "loading_model" | "recording" | "transcribing" | "error";
  [key: string]: unknown;
};

export type SidecarRpcMethodSystemInfoParams = {
};
export type SidecarRpcMethodSystemInfoResult = {
  capabilities: Array<string>;
  protocol: string;
  runtime: {
  cuda_available: boolean;
  platform: string;
  python_version: string;
  [key: string]: unknown;
};
  version: string;
  [key: string]: unknown;
};

export type SidecarRpcMethodSystemPingParams = {
};
export type SidecarRpcMethodSystemPingResult = {
  protocol: string;
  version: string;
  [key: string]: unknown;
};

export type SidecarRpcMethodSystemShutdownParams = {
  reason?: string;
};
export type SidecarRpcMethodSystemShutdownResult = {
  status: string;
  [key: string]: unknown;
};

export type SidecarRpcMethodName = "asr.initialize" | "asr.status" | "asr.transcribe" | "audio.list_devices" | "audio.meter_start" | "audio.meter_status" | "audio.meter_stop" | "audio.set_device" | "model.download" | "model.get_status" | "model.install" | "model.purge_cache" | "recording.cancel" | "recording.start" | "recording.status" | "recording.stop" | "replacements.get_preset_rules" | "replacements.get_presets" | "replacements.get_rules" | "replacements.preview" | "replacements.set_rules" | "status.get" | "system.info" | "system.ping" | "system.shutdown";
export type SidecarRpcRequiredMethodName = "asr.initialize" | "audio.list_devices" | "audio.meter_start" | "audio.meter_stop" | "audio.set_device" | "model.get_status" | "model.purge_cache" | "recording.cancel" | "recording.start" | "recording.stop" | "replacements.get_presets" | "replacements.get_rules" | "replacements.set_rules" | "status.get" | "system.info" | "system.ping" | "system.shutdown";
export type SidecarRpcOptionalMethodName = "asr.status" | "asr.transcribe" | "audio.meter_status" | "model.download" | "model.install" | "recording.status" | "replacements.get_preset_rules" | "replacements.preview";
export interface SidecarRpcMethodParamsMap {
  "asr.initialize": SidecarRpcMethodAsrInitializeParams;
  "asr.status": SidecarRpcMethodAsrStatusParams;
  "asr.transcribe": SidecarRpcMethodAsrTranscribeParams;
  "audio.list_devices": SidecarRpcMethodAudioListDevicesParams;
  "audio.meter_start": SidecarRpcMethodAudioMeterStartParams;
  "audio.meter_status": SidecarRpcMethodAudioMeterStatusParams;
  "audio.meter_stop": SidecarRpcMethodAudioMeterStopParams;
  "audio.set_device": SidecarRpcMethodAudioSetDeviceParams;
  "model.download": SidecarRpcMethodModelDownloadParams;
  "model.get_status": SidecarRpcMethodModelGetStatusParams;
  "model.install": SidecarRpcMethodModelInstallParams;
  "model.purge_cache": SidecarRpcMethodModelPurgeCacheParams;
  "recording.cancel": SidecarRpcMethodRecordingCancelParams;
  "recording.start": SidecarRpcMethodRecordingStartParams;
  "recording.status": SidecarRpcMethodRecordingStatusParams;
  "recording.stop": SidecarRpcMethodRecordingStopParams;
  "replacements.get_preset_rules": SidecarRpcMethodReplacementsGetPresetRulesParams;
  "replacements.get_presets": SidecarRpcMethodReplacementsGetPresetsParams;
  "replacements.get_rules": SidecarRpcMethodReplacementsGetRulesParams;
  "replacements.preview": SidecarRpcMethodReplacementsPreviewParams;
  "replacements.set_rules": SidecarRpcMethodReplacementsSetRulesParams;
  "status.get": SidecarRpcMethodStatusGetParams;
  "system.info": SidecarRpcMethodSystemInfoParams;
  "system.ping": SidecarRpcMethodSystemPingParams;
  "system.shutdown": SidecarRpcMethodSystemShutdownParams;
}
export interface SidecarRpcMethodResultMap {
  "asr.initialize": SidecarRpcMethodAsrInitializeResult;
  "asr.status": SidecarRpcMethodAsrStatusResult;
  "asr.transcribe": SidecarRpcMethodAsrTranscribeResult;
  "audio.list_devices": SidecarRpcMethodAudioListDevicesResult;
  "audio.meter_start": SidecarRpcMethodAudioMeterStartResult;
  "audio.meter_status": SidecarRpcMethodAudioMeterStatusResult;
  "audio.meter_stop": SidecarRpcMethodAudioMeterStopResult;
  "audio.set_device": SidecarRpcMethodAudioSetDeviceResult;
  "model.download": SidecarRpcMethodModelDownloadResult;
  "model.get_status": SidecarRpcMethodModelGetStatusResult;
  "model.install": SidecarRpcMethodModelInstallResult;
  "model.purge_cache": SidecarRpcMethodModelPurgeCacheResult;
  "recording.cancel": SidecarRpcMethodRecordingCancelResult;
  "recording.start": SidecarRpcMethodRecordingStartResult;
  "recording.status": SidecarRpcMethodRecordingStatusResult;
  "recording.stop": SidecarRpcMethodRecordingStopResult;
  "replacements.get_preset_rules": SidecarRpcMethodReplacementsGetPresetRulesResult;
  "replacements.get_presets": SidecarRpcMethodReplacementsGetPresetsResult;
  "replacements.get_rules": SidecarRpcMethodReplacementsGetRulesResult;
  "replacements.preview": SidecarRpcMethodReplacementsPreviewResult;
  "replacements.set_rules": SidecarRpcMethodReplacementsSetRulesResult;
  "status.get": SidecarRpcMethodStatusGetResult;
  "system.info": SidecarRpcMethodSystemInfoResult;
  "system.ping": SidecarRpcMethodSystemPingResult;
  "system.shutdown": SidecarRpcMethodSystemShutdownResult;
}

// Sidecar RPC notification params
export type SidecarRpcNotificationEventAudioLevelParams = {
  peak: number;
  rms: number;
  session_id?: string;
  source: "meter" | "recording";
  [key: string]: unknown;
};

export type SidecarRpcNotificationEventModelProgressParams = {
  current: number;
  current_file?: string;
  files_completed?: number;
  files_total?: number;
  stage?: string;
  total?: number | null;
  unit?: string;
  [key: string]: unknown;
};

export type SidecarRpcNotificationEventStatusChangedParams = {
  detail?: string;
  model?: Record<string, unknown>;
  progress?: Record<string, unknown>;
  state: string;
  [key: string]: unknown;
};

export type SidecarRpcNotificationEventTranscriptionCompleteParams = {
  confidence?: number;
  duration_ms: number;
  session_id: string;
  text: string;
  [key: string]: unknown;
};

export type SidecarRpcNotificationEventTranscriptionErrorParams = {
  kind: string;
  message: string;
  session_id: string;
  [key: string]: unknown;
};

export type SidecarRpcNotificationName = "event.audio_level" | "event.model_progress" | "event.status_changed" | "event.transcription_complete" | "event.transcription_error";
export interface SidecarRpcNotificationParamsMap {
  "event.audio_level": SidecarRpcNotificationEventAudioLevelParams;
  "event.model_progress": SidecarRpcNotificationEventModelProgressParams;
  "event.status_changed": SidecarRpcNotificationEventStatusChangedParams;
  "event.transcription_complete": SidecarRpcNotificationEventTranscriptionCompleteParams;
  "event.transcription_error": SidecarRpcNotificationEventTranscriptionErrorParams;
}

// Command name constants
export const COMMAND_CAN_START_RECORDING = "can_start_recording" as const;
export const COMMAND_CANCEL_RECORDING = "cancel_recording" as const;
export const COMMAND_CLEAR_HISTORY = "clear_history" as const;
export const COMMAND_COPY_LAST_TRANSCRIPT = "copy_last_transcript" as const;
export const COMMAND_COPY_TRANSCRIPT = "copy_transcript" as const;
export const COMMAND_DOWNLOAD_MODEL = "download_model" as const;
export const COMMAND_EXPORT_HISTORY = "export_history" as const;
export const COMMAND_GENERATE_DIAGNOSTICS = "generate_diagnostics" as const;
export const COMMAND_GET_APP_STATE = "get_app_state" as const;
export const COMMAND_GET_AVAILABLE_PRESETS = "get_available_presets" as const;
export const COMMAND_GET_CAPABILITIES = "get_capabilities" as const;
export const COMMAND_GET_CAPABILITY_ISSUES = "get_capability_issues" as const;
export const COMMAND_GET_CONFIG = "get_config" as const;
export const COMMAND_GET_HOTKEY_STATUS = "get_hotkey_status" as const;
export const COMMAND_GET_MODEL_CATALOG = "get_model_catalog" as const;
export const COMMAND_GET_MODEL_STATUS = "get_model_status" as const;
export const COMMAND_GET_RECENT_LOGS = "get_recent_logs" as const;
export const COMMAND_GET_REPLACEMENT_RULES = "get_replacement_rules" as const;
export const COMMAND_GET_TRANSCRIPT_HISTORY = "get_transcript_history" as const;
export const COMMAND_IS_ENABLED = "is_enabled" as const;
export const COMMAND_LIST_AUDIO_DEVICES = "list_audio_devices" as const;
export const COMMAND_LOAD_PRESET = "load_preset" as const;
export const COMMAND_PREVIEW_REPLACEMENT = "preview_replacement" as const;
export const COMMAND_PURGE_MODEL_CACHE = "purge_model_cache" as const;
export const COMMAND_RESET_CONFIG_TO_DEFAULTS = "reset_config_to_defaults" as const;
export const COMMAND_RESTART_SIDECAR = "restart_sidecar" as const;
export const COMMAND_RUN_SELF_CHECK = "run_self_check" as const;
export const COMMAND_SET_AUDIO_DEVICE = "set_audio_device" as const;
export const COMMAND_SET_ENABLED = "set_enabled" as const;
export const COMMAND_SET_HOTKEY = "set_hotkey" as const;
export const COMMAND_SET_REPLACEMENT_RULES = "set_replacement_rules" as const;
export const COMMAND_START_MIC_TEST = "start_mic_test" as const;
export const COMMAND_START_RECORDING = "start_recording" as const;
export const COMMAND_STOP_MIC_TEST = "stop_mic_test" as const;
export const COMMAND_STOP_RECORDING = "stop_recording" as const;
export const COMMAND_TOGGLE_ENABLED = "toggle_enabled" as const;
export const COMMAND_UPDATE_CONFIG = "update_config" as const;

// Event name constants
export const EVENT_APP_ERROR = "app:error" as const;
export const EVENT_AUDIO_LEVEL = "audio:level" as const;
export const EVENT_MODEL_PROGRESS = "model:progress" as const;
export const EVENT_MODEL_STATUS = "model:status" as const;
export const EVENT_RECORDING_STATUS = "recording:status" as const;
export const EVENT_SIDECAR_STATUS = "sidecar:status" as const;
export const EVENT_STATE_CHANGED = "state:changed" as const;
export const EVENT_TRANSCRIPT_COMPLETE = "transcript:complete" as const;
export const EVENT_TRANSCRIPT_ERROR = "transcript:error" as const;

// Sidecar RPC method name constants
export const RPC_METHOD_ASR_INITIALIZE = "asr.initialize" as const;
export const RPC_METHOD_ASR_STATUS = "asr.status" as const;
export const RPC_METHOD_ASR_TRANSCRIBE = "asr.transcribe" as const;
export const RPC_METHOD_AUDIO_LIST_DEVICES = "audio.list_devices" as const;
export const RPC_METHOD_AUDIO_METER_START = "audio.meter_start" as const;
export const RPC_METHOD_AUDIO_METER_STATUS = "audio.meter_status" as const;
export const RPC_METHOD_AUDIO_METER_STOP = "audio.meter_stop" as const;
export const RPC_METHOD_AUDIO_SET_DEVICE = "audio.set_device" as const;
export const RPC_METHOD_MODEL_DOWNLOAD = "model.download" as const;
export const RPC_METHOD_MODEL_GET_STATUS = "model.get_status" as const;
export const RPC_METHOD_MODEL_INSTALL = "model.install" as const;
export const RPC_METHOD_MODEL_PURGE_CACHE = "model.purge_cache" as const;
export const RPC_METHOD_RECORDING_CANCEL = "recording.cancel" as const;
export const RPC_METHOD_RECORDING_START = "recording.start" as const;
export const RPC_METHOD_RECORDING_STATUS = "recording.status" as const;
export const RPC_METHOD_RECORDING_STOP = "recording.stop" as const;
export const RPC_METHOD_REPLACEMENTS_GET_PRESET_RULES = "replacements.get_preset_rules" as const;
export const RPC_METHOD_REPLACEMENTS_GET_PRESETS = "replacements.get_presets" as const;
export const RPC_METHOD_REPLACEMENTS_GET_RULES = "replacements.get_rules" as const;
export const RPC_METHOD_REPLACEMENTS_PREVIEW = "replacements.preview" as const;
export const RPC_METHOD_REPLACEMENTS_SET_RULES = "replacements.set_rules" as const;
export const RPC_METHOD_STATUS_GET = "status.get" as const;
export const RPC_METHOD_SYSTEM_INFO = "system.info" as const;
export const RPC_METHOD_SYSTEM_PING = "system.ping" as const;
export const RPC_METHOD_SYSTEM_SHUTDOWN = "system.shutdown" as const;
